; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  tzapu/WiFiManager@^2.0.17

board_build.arduino.partitions = default_16MB.csv   ;  指定 16MB Flash 分区表 / Set the 16 MB Flash partition table
board_build.arduino.memory_type = qio_opi    ;  指定 Flash 和 PSRAM 的运行模式 / Set the Flash and PSRAM operating mode
board_upload.flash_size = 16MB    ;  指定 Flash 容量为 16MB / Set the Flash capacity to 16 MB

monitor_speed = 115200   ;  指定串口监视器的波特率为 115200 / Set the serial monitor baud rate to 115200
monitor_dtr = 0
monitor_rts = 0

build_flags =
  -DBOARD_HAS_PSRAM   ;  启用 PSRAM / Enable PSRAM
  -DARDUINO_USB_MODE=1   ;  使用 ESP32-S3 原生 USB 模式 / Use the ESP32-S3 native USB mode
  -DARDUINO_USB_CDC_ON_BOOT=1   ;  将 Serial 映射到 ESP32-S3 原生 USB CDC / Route Serial to native USB CDC
